MODEL:
  MLM_PROB: 0.15
  MIM_PROB: 0.4
  PRECISION: 'bf16'
  CHECKPOINT_PATH: ""
  DROPOUT: 0.1
  GPUS: 8
  TASK: ''
  NAME: ''
  MAX_SEQUENCE_LEN: 512
  IS_ORIGIN: False

DATASETS:
  TRAIN: ""
  VALID: ""
  TEST: ""

DATALOADER:
  NUM_WORKERS: 4
  NUM_PROC: 32
  NUM_FILES: 0

SOLVER:
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 10
  MAX_STEPS: 0
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 2
  WEIGHT_DECAY: 0.01
  WEIGHT_DECAY_BIAS: 0.0
  SCHED: "WarmupLinearLR"
  WARMUP_METHOD: "linear"
  WARMUP_STEP_RATIO: 0.05
  WARMUP_FACTOR: 0.01
  GAMMA: 0.9
  AGB: 1
  TRAIN_BSZ: 16
  VALID_BSZ: 32

WANDB:
#  KEY: ''
  KEY: '494def72eaf3d56f1ae73c659007c49aa4accc82'

OUTPUT_DIR: "/home/shili/Dict/Tensor_borad"

